development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql 
  url: postgres://axgjnehxbhwkuq:SYG8niMlDyCUKIPDT-VrTjjeWw@ec2-54-163-248-218.compute-1.amazonaws.com:5432/d4pjomlbnl5e2c